# Generated by Django 5.2.17 on 2026-09-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="image",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.URLField(blank=True),
        ),
    ]
