# Generated by Django 5.2.17 on 2026-09-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_club_is_rejected_mediaasset"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventreminder",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="eventreminder",
            name="sent_for_start_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
