# Generated by Django 5.2.17 on 2026-09-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_eventreminder_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="report",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="report_photos",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
