# Generated by Django 5.2.17 on 2026-09-25 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_projectchatread_projectmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="projectmessage",
            index=models.Index(
                fields=["project", "sender", "created_at"],
                name="core_projec_project_82df2e_idx",
            ),
        ),
    ]
